### ISSUE TITLE
Who uses `unimported`

### ISSUE THREAD

**Issue by smeijer** [smeijer/unimported#1]
Hi there!

If your company is using `unimported`, please let us know who you are, so we can mention you in the README and forthcoming website.

Instructions:

- Share your project / company name
- Share your logo _(in which case it might be used in the readme / frontpage etc)_
- If your project is open source or public, please share a link!
- If possible, tell us how many files/modules you were able to remove with the help of `unimported`

Thanks for sharing!

**Comment by kerbe** [comment]
Hello,
I can report in that my company is using unimported.
Company name: Lunanova
Logo: 
![Lunanova](https://user-images.githubusercontent.com/47280420/80595850-14c7f980-8a2e-11ea-9eba-919da178547c.png)
Project isn't open source, and not public yet. But once it goes live, I try to remember update here.

This far I was able to reduce one direct dependency from deployment, which resulted 97 deps of that being removed. Which is quite nice, and this was just first pass and quick look on things.

**Comment by gajus** [comment]
We are using at http://contra.com/

**Comment by damien-monni** [comment]
I'm using it in all my projects! I'm a freelance: https://damien-monni.com

**Comment by dabyland** [comment]
We're using Unimported @ [Rentvine](https://www.rentvine.com/) and loving it! I've been searching for an easy CLI tool to do the dirty work of finding our unused files (there's a lot of em). Hoping to integrate it into our pipeline in the future and report results.

Much appreciate the hard work and great documentation!

**Comment by ritingliudd01** [comment]
We are using at https://www.hk01.com/
