### ISSUE TITLE
[Feat] Add flags for output customization

### ISSUE THREAD

**Issue by Tbhesswebber** [smeijer/unimported#106]
It would be great to be able to customize the output using flags to make the output more consumable from within CI environments.  I'd be more than happy to tackle some of this as it will be immediately useful for me

### Usage
Out of the gate, I can think of two things that might be valuable - output serialization and output narrowing.

#### Serialization

```sh 
# syntax | option could be one of pretty(default), json, or text (raw list)
$ unimported --format <option>
$ unimported -f <options>
```

#### Narrowing

```sh
# syntax | option could be any of unresolved, unimported, or unused
$ unimported --output <option> --output <option> --output <option>
$ unimported -o <option> -o <option> -o <option>
```

#### Using static checks for unresolved imports

```sh
unimported -o unimported -o unused
```

#### Reporting summary in a PR comment from a GitHub Action

```sh
# get the summary and save it to an output
echo '::set-output name=UNIMPORTED_SUMMARY::$(unimported -f json | jq ".summary")'
# in the next step of the job, create the comment
```

#### Create annotations in package.json for unused deps in a GitHub Action

```sh
# get a raw list of unused dependencies
echo '::set-output name=UNUSED_DEPS::$(unimported -f text -o unused)'
# in the next step of the job, create an annotation for each line of the output (could also use JSON here 🤷‍♂️ )
```

**Comment by smeijer** [comment]
This would be very nice to have! Especially the "github reporter".

We've already separated the "printer" from the "parser", so this shouldn't be too complicated to add either.

Do you still want to take a stab at it?

**Comment by smeijer** [comment]
Partially fixed by #139

**Comment by adrian-gierakowski** [comment]
json format for consumption by other programs would be great

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
