### ISSUE TITLE
[Request] Allow to config ignore entries

### ISSUE THREAD

**Issue by vimutti77** [smeijer/unimported#108]
### Problem
Given the directory structure
```
pages/
  app/
    _a/
      1.tsx
    b/
      _2.tsx
      3.tsx
      4.tsx
    c/
      5.tsx
    6.txt
```
I want every files except files or folder that start with `_` to be entries. So it should match only
```
pages/app/b/3.tsx
pages/app/b/4.tsx
pages/app/c/5.tsx
pages/app/6.tsx
```

### Feature Request
I want to specify something like
```json
{
  "entry": ["pages/**/*.tsx"],
  "ignoreEntries": ["**/_*", "**/_*/**"]
}
```
Or may be like this
```json
{
  "entry": [
    {
      "file": "pages/**/*.tsx",
      "ignore": ["**/_*", "**/_*/**"]
    }
  ]
}
```

**Comment by smeijer** [comment]
This can already be done by utilising the globs

```
"entry": ["/pages/**/!(_)*/**/!(_)*.tsx"],
```

See here for example: https://globster.xyz/?q=%2Fpages%2F**%2F!(_)*%2F**%2F!(_)*.tsx&f=%2Fpages%2Fapp%2F_a%2F1.tsx%2C%2Fpages%2Fapp%2Fb%2F_2.tsx%2C%2Fpages%2Fapp%2Fb%2F3.tsx%2C%2Fpages%2Fapp%2Fb%2F4.tsx%2C%2Fpages%2Fapp%2Fc%2F5.tsx%2C%2Fpages%2Fapp%2F6.tsx

**Comment by vimutti77** [comment]
@smeijer I want to ignore every sub directory too, such as `/pages/app/_a/x/1.tsx`, How I can do it?

**Comment by smeijer** [comment]
Please see the example, and optionally update the glob to your needs. The example structure that you've posters, is covered there.

**Comment by vimutti77** [comment]
I am not sure that glob will cover my use case. I tried with `/pages/**/!(_)*/**/!(_)*.tsx` but it's still not work.

In this [example](https://globster.xyz/?q=%2Fpages%2F**%2F!(_)*%2F**%2F!(_)*.tsx&f=%2Fpages%2Fapp%2F_a%2F1.tsx%2C%2Fpages%2Fapp%2F_a%2Fa%2F2.tsx%2C%2Fpages%2Fapp%2F_a%2Fa%2Fa%2F3.tsx%2C%2Fpages%2Fapp%2Fb%2F_4.tsx%2C%2Fpages%2Fapp%2Fb%2F5.tsx%2C%2Fpages%2Fapp%2Fb%2F6.tsx), I want it to match only `/pages/app/b/5.tsx` and `/pages/app/b/6.tsx`

**Comment by smeijer** [comment]
Does this work for you?

```
/pages/app/!(_)*/!(_)*.tsx 
```

Note that you can define multiple patterns, you're not limited to a single one.

I assume that you have a finite nesting, maybe a level of 5 deep at most? I haven't tested this solution, but I'd expect this to work:

```
entry: [
  '/pages/app/!(_)*/!(_)*.tsx',
  '/pages/app/*/!(_)*/!(_)*.tsx', 
  '/pages/app/*/*/!(_)*/!(_)*.tsx', 
]
```

**Comment by smeijer** [comment]
I wonder if it would make sense to also apply `ignorePatterns` to the entry files. Then we can cover your needs with that. What do you think?

**Comment by vimutti77** [comment]
In my use case, it can be infinite nesting. So, I think `ignorePatterns` would easily cover my use case with the config like this
```
  "entry": [
    {
      "include": "pages/**/*.tsx",
      "exclude": ["**/_*", "**/_*/**"]
    },
    "other/entry.ts",
  ]
```

**Comment by smeijer** [comment]
Can you submit a pull-request adding that feature?

**Comment by vimutti77** [comment]
@smeijer I have submitted the PR
