### ISSUE TITLE
[Request] Also check on dynamic imports

### ISSUE THREAD

**Issue by Bertijn** [smeijer/unimported#109]
Problem

I wanted to use this library to check for unimported code, but my entry file has a lot of dynamic imports and it appears the library doesn't take these imports into account:

import('./helpers/androidKeyboard').then((_) => {
    _.attachMobileKeyboardListener();
});

Feature Request

Also make sure to parse the dynamic imports

**Comment by smeijer** [comment]
Dynamic imports are supported. Can you share a reproduction?

https://github.com/smeijer/unimported/blob/3ae5b53b0df9482a857634ae91328ad38597599b/src/traverse.ts#L281-L284
