### ISSUE TITLE
unresolved imports contains file imports with resourceQuery (e.g. 'filename.ext?query')

### ISSUE THREAD

**Issue by dzsodzso63** [smeijer/unimported#113]
Consider the following import:
 
`import ImgAsComponent from 'img/thing.svg?component';`

As no alias or pattern ignore or wildcards apply for **unresolved imports**, these imports will be reported, and no configuration can help this

**Comment by smeijer** [comment]
Is that even valid? I'm curious, why would you want to import using a query? What's the use case of that?

Happy to add support if it's indeed a valid import pattern.

**Comment by smeijer** [comment]
Webpack simply strips the resource query, we should do the same:

https://github.com/import-js/eslint-plugin-import/blob/328064abc707d3289772a8a29da5783c6dc345f6/resolvers/webpack/index.js#L46-L50

**Comment by ahuet67** [comment]
@smeijer some lib recommands to call webpack loader in the code file. And sometimes, there are plugins in the query parameters of the import.

This is my case with this lib : https://github.com/jgranstrom/sass-extract-loader

**Comment by ngouy** [comment]
same issue with "something.service.ts" for example. Which is very valid no?

**Comment by AlexJDG** [comment]
This can be resolved using a path transform like so 

```
.unimportedrc.json
{
  ...
  "pathTransforms": {
    "(.*)\\?(?:.*)$": "$1"
  },
  ...
}
```

**Comment by ngouy** [comment]
I went back to it, bumping to node 20 fixed it??
All good on my end

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
