### ISSUE TITLE
unresolved imports contains not used packages

### ISSUE THREAD

**Issue by dzsodzso63** [smeijer/unimported#114]
sometimes no way to solve where they came from

some has mentioned deep in `node_modules`, which is an ignored pattern, some is peer dependency of a sub-dependency in `package-lock.json`

example:

```
   1 │ pnpapi
   2 │ @swc/core
   3 │ @swc/core/package.json
   4 │ esbuild
   5 │ esbuild/package.json
   6 │ @parcel/css
   7 │ lightningcss
...
  52 │ encoding
  53 │ bufferutil
  54 │ utf-8-validate
  55 │ csv-stringify/sync

```

**Comment by smeijer** [comment]
Please be sure to install dev dependencies as devDependency.
