### ISSUE TITLE
Doesn't work with non-default exports

### ISSUE THREAD

**Issue by angelod1as** [smeijer/unimported#116]
I run `npx unimported` in my project's root and it shows me 873 unimported files.

All of them are imported somewhere, but as non-default exports: `import { function } from './file.tsx'`

Is there something I need to do to enable this?

**Comment by el-j** [comment]
i had the same problem, so i create a fresh `create-react-app` with typescript to get unimported to work properly...
the config i figured out, to at least show the `UnimportedFile.tsx` as unimported.

maybe it helps here.

```json
{
  "entry": [
    "src/index.tsx"
  ],
  "rootDir": ".",
  "ignorePatterns": [
    "**/node_modules/**",
    "**/*.tests.{js,jsx,ts,tsx}",
    "**/*.test.{js,jsx,ts,tsx}",
    "**/*.spec.{js,jsx,ts,tsx}",
    "**/tests/**",
    "**/__tests__/**",
    "**/*.d.ts"
  ],
  "moduleDirectory": [
    "node_modules",
    ".",
    "./src"
  ],
  "ignoreUnimported": [],
  "ignoreUnused": [],
  "ignoreUnresolved": []
}
```

<img width="487" alt="image" src="https://user-images.githubusercontent.com/2795534/204013430-f6aef75b-2476-41c7-9e19-32c302021503.png">

**Comment by el-j** [comment]
... but sadly in my lager own project i cannot get it to work the same way ... could there be any problem with hooks or react-router or something?

**Comment by smeijer** [comment]
Named exports/imports work properly. The issue is likely to be something else. Perhaps import aliases? Or a mismatched root dir?

**Comment by davidalvarezr** [comment]
I encountered the same problem and adding
```
"main": "./path/tomymain/Component.tsx",
```
fixed the problem
