### ISSUE TITLE
Globs for file paths

### ISSUE THREAD

**Issue by olidacombe** [smeijer/unimported#12]
It would be really useful (for me at least) to use globs in file path specifications (i.e. `entry` and `ignoreUnimported`), not just pattern specifications (e.g. `ignorePatterns`).

So my `.unimportedrc.json` could look like this and work as expected:

```
{
  "entry": ["src/index.tsx", "src/**/*.test.{j,t}s"],
  "ignoreUnresolved": [],
  "ignoreUnimported": "src/setup{Proxy,Tests}.js",
  "ignoreUnused": [],
  "ignorePatterns": ["**/node_modules/**", "**/*.d.ts"]
}
```

**Comment by smeijer** [comment]
Closed by 650827ae2564754b5ef6260bfb9356e9018cc57c
