### ISSUE TITLE
WorkingHowTo for Create-React-App Typscript with hooks and router

### ISSUE THREAD

**Issue by el-j** [smeijer/unimported#120]
Hi i now have tried many many different configurations to get it to work in my big typescript project.

the only thing works seems to be the pattern for the subdirectory directly in the entry point, 
but if i use it. the unimported testfiled i created will be listed as entrypoint and so it is not shown as `unimported` ... 
please help to configure. i guess an working example config for a `react-create-app --template: typescript` and 
together with the react router and lazyload would be very nice ... 
```json
"entry": ["src/index.tsx", "src/pages/**/*.{tsx}"],
```

in a fresh project i could use this config to get the right results, but it does not have lazy load nor any hooks or router integrated. 
could you please advice or point into the right direction how to debug and find the right config to find my unimported files. 

```json
{
  "entry": [
    "src/index.tsx"
  ],
  "rootDir": ".",
  "ignorePatterns": [
    "**/node_modules/**",
    "**/*.tests.{js,jsx,ts,tsx}",
    "**/*.test.{js,jsx,ts,tsx}",
    "**/*.spec.{js,jsx,ts,tsx}",
    "**/tests/**",
    "**/__tests__/**",
    "**/*.d.ts"
  ],
  "moduleDirectory": [
    "node_modules",
    ".",
    "./src"
  ],
  "ignoreUnimported": [],
  "ignoreUnused": [],
  "ignoreUnresolved": []
}
```

**Comment by smeijer** [comment]
Sorry, I don't have the capacity for support questions. I'm closing this issue, as it's an implementation question and not a limitation or bug in this project.
