### ISSUE TITLE
Unable to resolve Vite aliases

### ISSUE THREAD

**Issue by smallbatch-apps** [smeijer/unimported#130]
We use Vite for our application, as a number of people no doubt do. We have set up a number of aliases in the `vite.config.js` file. For example, `'@components': path.resolve(__dirname, 'src/components)`. Any components imported this way cannot be seen by this tool.

While this is a relatively recent change and not many components are called using this syntax there are at least a few false positives in our app (in addition to the nearly 40 true positives). 

This inability to resolve aliases may also affect TypeScript config aliases as well, I have not been able to test that.

**Comment by smeijer** [comment]
We do resolve aliases from typescript configs, and it's also possible to define them via the unimported config file.

See the readme for:

```
{
  "aliases": {
    "@components/*": ["./components", "./components/*"]
  }
}
```

 I'm happy to accept a pr that adds support for aliases defined in `vite.config.js` tho.
