### ISSUE TITLE
exporting counts as importing

### ISSUE THREAD

**Issue by abejfehr** [smeijer/unimported#137]
I have a project that has many files, and [barrel files](https://adrianfaciu.dev/posts/barrel-files/) that re-export things.

As soon as something is imported, even via an `export`, it's no longer correctly flagged as unimported.

## Reproducible example

```
// index.js

import { B } from "./barrel";

console.log(B);

```

```
// barrel.js

export { A } from './A';
export { B } from './B';

```

```
// A.js

export const A = 'A';
```

```
// B.js

export const B = 'B';
```

## Expectation

unimported should say that 'A.js' is unimported (it's never imported in index.js)

## Actual result

unimported says: 

```
✓ There don't seem to be any unimported files.
```

Being able to track unused exports would be very valuable in finding dead code 🙏 

I would just use tree shaking in a bundler if I could, but I need the ability to remove those files from the repo.

**Comment by abejfehr** [comment]
This does not seem trivial to implement 😅 

It looks like A.js will always be "imported" [because it was visited during traversal](https://github.com/smeijer/unimported/blob/main/src/process.ts#L40).

I wonder if I can configure a bundler into telling me what's tree shakeable instead so I know what to remove

**Comment by abejfehr** [comment]
It turns out [ts-prune](https://www.npmjs.com/package/ts-prune) handles this case actually, thank you for listing related libraries in your README.md 🙏

**Comment by smeijer** [comment]
This isn't in the scope of unimported. The file is imported, and thereby the current output is correct. We don't analyze dead code. There are other/better tools for that.

**Comment by joernroeder** [comment]
> There are other/better tools for that.

any recommendation @smeijer? thx
