### ISSUE TITLE
--fix to delete unused files and packages

### ISSUE THREAD

**Issue by tomfa** [smeijer/unimported#138]
I would love the ability to `--fix` to delete unused files, and/or remove unused packages.

**Use case:** 
I am creating a new app from an existing app. It'll contain ~20% of the existing app.
By removing the endpoints, I get a report of unused files and packages, but will have to delete them manually (or create a script).

**Comment by tomfa** [comment]
Thanks for a super helpful package ❤️

**Comment by tomfa** [comment]
I might! Here's how I'd imagine doing it:

- add a flag `--delete-unused-files`
- abort if there are unresolved imports (as the unused files might actually be used)
- delete them at the end of the script (no prompt, as the flag is descriptive enough)

Does this seem reasonable? 

_I imagine a future PR could add the flags `--delete-unused-packages` (and maybe a combined `--delete-unused`)_

**Comment by smeijer** [comment]
Sounds good. I wonder tho, why not just a single `--fix` and fix whatever we can? I assume users would first run without the `--fix` to inspect the errors, and use version control for easy reverts? That way we behave similiar to for example eslint.

We could also print a hint in the analyze result to run `unimported --fix` to resolve (some of) the issues.

**Comment by tomfa** [comment]
I agree with `--fix` being a good solution and arg name (maybe the best). 

Having separate `--delete-unused-packages` +`--delete-unused-files` (and a combined flag for doing both) _might_ support some edge cases we don't think of. 

_To be honest, the main reason (for me) to split them in two separate flags (and PRs) is that I think it'll increase the odds that I'll find time and motivation to make a PR. 😅_

**Comment by tomfa** [comment]
Added a draft PR here: https://github.com/smeijer/unimported/pull/141

**Comment by smeijer** [comment]
Closed by #142
