### ISSUE TITLE
[Request] Exit code in case of `show-` option

### ISSUE THREAD

**Issue by yyamanoi1222** [smeijer/unimported#144]
Hi!
I'm going to use this package in CI environment.
I'm only interested in the section `unimported files`, So I use the option `show-unused-files`.
But status code is not considered by report type.
For example, There are not unimported files but status code is 1  because of there are unresolved imports.
I suggest that the logic to determine the status code checks only the selected report type if `show-` option passed.
I would like your opinion on this proposal.

**Comment by smeijer** [comment]
I agree that the by you described behavior should be implemented. Can you submit a pull request?

**Comment by yyamanoi1222** [comment]
@smeijer Thank you for your reply. I gonna send a pull request.
