### ISSUE TITLE
Support full vue3 syntax

### ISSUE THREAD

**Issue by jakob-lilliemarck** [smeijer/unimported#159]
Hey,
thanks for an awesome library, I've been using it alot with vue 2 and it has been working out great!

We've recently switched to Vue 3 and in doing so I noticed that unimported doesn't seem to fully support Vue 3 single file component syntax. More specifically, in Vue 3 multiple `<script>` tags in a single file is considered valid, and up until recently it's been the only way to export named values from single file components, like typescript interfaces, enums, etc.

here's a link to vue documentation on the topic:
https://vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script

Currently trying to run `npx unimported` on a vue 3 typescript project that uses that syntax, will just return
```
Failed parsing /path/to/component.vue
```

It would be great to get full support for Vue 3 SFC syntax as per the documentation above.

**Comment by Pandazaur** [comment]
I had the same issue. Using `[defineOptions](https://vuejs.org/api/sfc-script-setup.html#defineoptions)` you might be able to have only one `<script setup>`

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
