### ISSUE TITLE
Running on Next.js projects

### ISSUE THREAD

**Issue by jheyer159** [smeijer/unimported#16]
Hello, thanks for making this tool!  
I'm attempting to use it on a next.js project and wondering if this can be configured to do so.

It seems that each page under the directory `pages` would be considered a separate entry point.  I tried listing each page as an entry point, but the output is showing them as unimported.  I'm assuming because they don't import each other.  Ideally the config would be `entry: ["pages/**"]` 

Am I going about this correctly? 

There are example repos [here](https://github.com/vercel/next.js/tree/canary/examples)

**Comment by smeijer** [comment]
I think that would be supported if we merge #13. I'll test it tomorrow, and merge if it works against your example repo.

**Comment by smeijer** [comment]
It took a bit longer but I just published `1.6.0`, which adds support for nextjs. :tada:
