### ISSUE TITLE
Support Vue SFC Syntax - multi-line <script> tag

### ISSUE THREAD

**Issue by subdavis** [smeijer/unimported#162]
Similar to #159 

## Works properly

```ts
<script lang="ts" setup>
/** This code will get parsed! */
<script>
```

## Does not work

Common tools like prettier with [singleAttributePerLine](https://prettier.io/docs/en/options.html#single-attribute-per-line) will format a Vue SFC like this.

```ts
<script
  lang="ts"
  setup
>
/** This code will not get parsed */
<script>
```

## solution

Unfortunately because the regex works line-by-line, it's not possible to simply fix the script regex.  The change needed to fix this bug  requires a more complicated change to how script extraction works.

**Comment by smeijer** [comment]
Can you submit a pull request? I'd be happy to add support for that. Even tho I'm a bit surprised by that syntax. 😅

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
