### ISSUE TITLE
Add support for react-native metro bundler wildcard imports

### ISSUE THREAD

**Issue by pke** [smeijer/unimported#166]
react-native metro bundler allows for `import from "./services/*.service.ts"` but `unimported` marks all `*.service.ts` files as unimported. Maybe this can already be solved by a config setting?

**Comment by smeijer** [comment]
Interesting. Is it like a glob? Of does it expand to an fixed set of names? Does it only work with unnamed imports? Or can you also import those files to an array, like vite import globs?

**Comment by alburdette619** [comment]
I got this to work in #200 & posted my necessary config.

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
