### ISSUE TITLE
[Feature Request] Make configurable the 'src' in traverse baseUrl  

### ISSUE THREAD

**Issue by ritingliudd01** [smeijer/unimported#167]
Many thanks for the great tool. The best ever!

Our team uses Nextjs from v9 and some source codes are outside of `./src` folder. When running `npx unimported`, the unused files do not cover those under non-`./src` folders such as `./modules`.

Would it be possible to make the `src` configurable in this line? Or even better to make it an array like ['./src', './module'].

`const baseUrl = (await fs.exists('src', cwd)) ? join(cwd, 'src') : cwd;` at https://github.com/smeijer/unimported/blob/c266dfa3b0cda097475959a385bf248ff2b957c7/src/index.ts#L247

Regards & Thanks,
Riting

**Comment by smeijer** [comment]
Hi, that should indeed be configurable. Are you able to submit a pull request?

**Comment by ritingliudd01** [comment]
> Hi, that should indeed be configurable. Are you able to submit a pull request?

OK. Let me try :)

**Comment by ritingliudd01** [comment]
@smeijer Done. Please review at https://github.com/smeijer/unimported/pull/168 Thanks :)

**Comment by smeijer** [comment]
Closing as resolved.
