### ISSUE TITLE
Respect .gitignore

### ISSUE THREAD

**Issue by scottyantipa** [smeijer/unimported#173]
Is there a way to have unimported automatically respect files in .gitignore for certain actions? For example, ignore unimported files that are in gitignore.

**Comment by itpretty** [comment]
That is a really good feature that most of projects might need.

**Comment by smeijer** [comment]
That'd be indeed a great feature to have. It shouldn't be too hard when using https://www.npmjs.com/package/ignore.

A PR would be much appreciated.

**Comment by smeijer** [comment]
Fixed by #184
