### ISSUE TITLE
How to deal with test files?

### ISSUE THREAD

**Issue by richardaum** [smeijer/unimported#175]
I'm currently using this library to analyze and detect unused files in my project. I've encountered a challenge when it comes to handling test files.

I've tried two strategies:

1. **Ignoring test files**: 
   - When I add the test files to the ignored patterns, it occasionally excludes source files that are unimported by other source files. This, however, results in unresolved imports in the test files.
   
2. **Setting test files as entry points**: 
   - By doing this, the library doesn't exclude source files that are only used by the test files. Ideally, I'd like these source files to be flagged as unimported.

Essentially, what I'm aiming for is:
- To have source files flagged as unimported if they're only used by test files.
- Correspondingly, if those source files are only used by test files, the test files should be also flagged as unimported.

Could you provide guidance on how to configure the library to achieve this desired behavior? Any suggestions or best practices would be greatly appreciated!

Thank you for your time and assistance.

**Comment by smeijer** [comment]
We don't cover test files at the moment. It's not as easy as just including them, as it would also mean devDependencies have to be analyzed.

So the recommendation is to ignore test files. 

> Essentially, what I'm aiming for is:
> To have source files flagged as unimported if they're only used by test files.

That's exactly the way it works today. By excluding the test files, any files that are only imported by test files, are now unimported and flagged. Same for dependencies. If the dependency is not used in production code, it should move to devDependencies, where it's ignored by unimported.

If that's not the behavior you're seeing, then please confirm the file is indeed used by a production file and can be reached via one of the defined entry points. All we need for a reproduction is a few files with only import statements that simulate your import graph.

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
