### ISSUE TITLE
unimported doesn't work if package.json version is not semver

### ISSUE THREAD

**Issue by greyscaled** [smeijer/unimported#176]
👋🏻 Hey there!

This issue is an extension of #83 .

`unimported` uses [read-pkg-up](https://www.npmjs.com/package/read-pkg-up): https://github.com/search?q=repo%3Asmeijer%2Funimported%20read-pkg-up&type=code

which, by default, attempts to normalize the closest package.json:

https://github.com/npm/normalize-package-data#what-normalization-currently-entails

I have a private project that uses the version string for date-based annotations. I therefore cannot use `unimported` on it (or even run commands like `--show-config`.

I'm wondering if:

1. We can simply just `readPackageUp({ normalize: false })` (I can try this out in a fork)
    - This seems fine to me for what this module does, but I don't have the full extent. Is there a strong reason to need the normalizations?
2. And if so, find an alternative, since there's no way to use `read-pkg-up` with it's current API to bypass normalizing the `version`.

An example output I get right now is:

> Error: Invalid version: "v2023-08-09.1"
>     at Object.fixVersionField (/home/greyb/.npm/_npx/9ed089bcb68ee34f/node_modules/normalize-package-data/lib/fixer.js:191:13)
>     at /home/greyb/.npm/_npx/9ed089bcb68ee34f/node_modules/normalize-package-data/lib/normalize.js:32:38
>     at Array.forEach (<anonymous>)
>     at normalize (/home/greyb/.npm/_npx/9ed089bcb68ee34f/node_modules/normalize-package-data/lib/normalize.js:31:15)
>     at module.exports (/home/greyb/.npm/_npx/9ed089bcb68ee34f/node_modules/read-pkg/index.js:20:36)
>     at async module.exports (/home/greyb/.npm/_npx/9ed089bcb68ee34f/node_modules/read-pkg-up/index.js:14:16)

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
