### ISSUE TITLE
Breaks when using `satisfies`

### ISSUE THREAD

**Issue by nevnein** [smeijer/unimported#177]
As per title, TypeScript syntax >=4.9 (possibly lower) will throw a `Failed parsing …` error. 

If this is intended behaviour maybe a maximum compatible TS version should be specified in the docs.

Thank you for your work.

**Comment by smeijer** [comment]
Thanks! I think this should be a matter of updating the typescript parser that we use. A PR would be most welcome.

**Comment by MathiasVandePol** [comment]
created a PR for this:https://github.com/smeijer/unimported/pull/181

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
