### ISSUE TITLE
Upgrade TS to 4.1+

### ISSUE THREAD

**Issue by FlorianWendelborn** [smeijer/unimported#18]
Just ran this on a TS 4.1+ project that used the following syntax:

```typescript
type X = `${Extract<NAMESPACE, string>}/${Extract<ACTION, string>}`
```

Since that’s the only file that crashed `unimported`, I’m pretty sure that this is related to depending on an old version of `@typescript-eslint/typescript-estree` which doesn’t support this feature yet.

---

### Workaround

Add this to your `package.json`:

```json
{
	"resolutions": {
		"@typescript-eslint/typescript-estree": "4.15.0"
	}
}
```

**Comment by smeijer** [comment]
Done, fixed in `1.7.0`.
