### ISSUE TITLE
unimported traverses node_modules when module name is not in dependencies

### ISSUE THREAD

**Issue by ryanwilsonperkin** [smeijer/unimported#187]
When a module from node_modules ends up being imported but is not explicitly in dependencies, `traverse` will import and parse the module as a source file and will continue traversal throughout node_modules despite it being potentially prohibitively expensive.

Related to the performance issues on node_modules mentioned in #62 

There should likely be a check to see if the resolve module name ends up including `node_modules` in the name and skipping traversal if this is the case.

**Comment by ryanwilsonperkin** [comment]
Reproduction: https://github.com/ryanwilsonperkin/unimported-issue-187

**Comment by smeijer** [comment]
I think there's a bug in when the ignore patterns are applied. I believe we first parse the full tree, and then only filter before printing the results. It would make more sense to check the import against ignore patterns when it's first read, and then stop walking down that tree if it should be ignored.

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
