### ISSUE TITLE
Dependency flagging is wrong when importing files from external dependencies

### ISSUE THREAD

**Issue by jeanbmar** [smeijer/unimported#189]
The following gets flagged as unresolved:
```
   1 │ @comp/interop/lib/interop/pub/flow/index.mjs
   2 │ @comp/interop/lib/interop/pub/io/index.mjs
   3 │ @comp/interop/lib/interop/priv/s3/putObject/index.mjs
```

While the lib gets flagged as unused:
```
1 │ @comp/interop
```

It seems like this module doesn't support the direct import of files from external dependencies?

**Comment by smeijer** [comment]
> It seems like this module doesn't support the direct import of files from external dependencies?

Yeah, I don't think we currently support that. A PR would be much appreciated.

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
