### ISSUE TITLE
`--config` seems to be broken

### ISSUE THREAD

**Issue by alexeyr** [smeijer/unimported#199]
I was trying to use `unimported --config tmp/.unimportedrc.json`, but it wasn't working in the way I expected. In fact, `unimported --config tmp/.unimportedrc.json --show-config` showed the same config as from `.unimportedrc.json`.

So I found the PR introducing it https://github.com/smeijer/unimported/pull/127/files and noted it had
```
  const configFile = await readJson<Partial<UnimportedConfig>>(
    args?.config || CONFIG_FILE,
  );
```
but in the equivalent place in the current code https://github.com/smeijer/unimported/blob/main/src/config.ts#L138-L144
```
  const cosmiconfigResult = cosmiconfigSync('unimported').search();
  const configFile = cosmiconfigResult?.config as Partial<UnimportedConfig>;
```
`args?.config` doesn't seem to be used. Or anywhere else that I could find.

Note I'm seeing the issue on 1.30.0 due to https://github.com/smeijer/unimported/issues/196. but again, from looking at the code it seems to still be there.

It isn't a high priority for me, because now that I know the issue, I can switch to JS config as a workaround.

**Comment by alexeyr** [comment]
It looks like the fix could be simply
```
const cosmiconfigResult = args?.config ?
  cosmiconfigSync('unimported').load(args.config) :
  cosmiconfigSync('unimported').search();
```

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
