### ISSUE TITLE
add support for webpack alias

### ISSUE THREAD

**Issue by xyy94813** [smeijer/unimported#20]
Cannot detect the imported file if a project not use relative path import.

For example,  use `babel-plugin-module-resolver`:

```json
// .babelrc
{
  "plugins": [
    [ "module-resolver", {
       "alias": {
          "@": "./src"
        }
     }]
  ]
}
```
or use webpack `resolve. alias`

```js
module.exports = {
  //...
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src')
    }
  }
};
```

**Comment by smeijer** [comment]
At the moment, only typescript aliases are supported. I think we can add support for webpack, but I'm not sure what to do with babel. Babel configs are highly dynamic. 

An alternative would be to add an additional mapping to `.unimportedrc.json` which would have a similar syntax to the typescript (tsconfig#paths) variant.

**Comment by xyy94813** [comment]
I'm a little confused as to why this is directly related to Webpack.

What we need to do more than find all the files that were imported by parsing,
and compare them to the files in the directory?

It doesn't matter which way we use to set the alias in project.

**Comment by smeijer** [comment]
Node doesn't support something like import aliases, that's why you declare them in your webpack config. This project does read import aliases from tsconfig, but not from a webpack config. Hence, it doesn't resolve the aliased file paths.

It's not related to webpack itself. It's related to you using import aliases.

**Comment by Slapbox** [comment]
@smeijer thanks for this great project! I wonder if there's some method I'm overlooking to deal with a situation like this:

We have a monorepo with a lot of shared code, and then some platform-specific code with package names like `our-utils-platform` - which will resolve to `our-utils-web` in Webpack and `our-utils-react-native` for React Native.

Is there any way to accommodate both of these circumstances with the current configuration capabilities? As it is right now, `out-utils-platform` can't be resolved by this tool. I see we could include an alias - but what about in a case where for different entry points, they need different aliases?

Thank you again for this great project!

**Comment by Slapbox** [comment]
With `--show-config` I see there's an `entryFiles` field with `aliases` beneath it. Is this a pattern we can use directly in our `.unimportedrc.json`? I'm guessing yes and working on that now.

**Comment by smeijer** [comment]
Hi @Slapbox , it is possible to specify `entryFiles` via the config file. Does that help?

```json
{
  "entry": ["src/main.ts", "src/pages/**/*.{js,ts}"],
}
```

**Comment by Slapbox** [comment]
Hey @smeijer, thanks for your reply!

What I mean is to allow resolutions to be set on a per-entry basis. So in your example, maybe `entry[0]` would need to resolve `our-utils-platform` to `our-utils-node` and in `entry[1]` would need to resolve `our-utils-platform` to `our-utils-web`.

It seems like `unimported` makes a configuration like that of its own behind the scenes that looks like below, and it would be great if we could set the same type of config from the `.unimportedrc.json`


```js
"entryFiles": [
    {
      "file": "src/main.ts",
      "aliases": {
        "our-utils-platform": "our-utils-node
      },
      "extensions": [ ".js", ".ts", ".tsx" ]
    },
    {
      "file": "src/pages/**/*.{js,ts}",
      "aliases": {
        "our-utils-platform": "our-utils-web
      },
      "extensions": [ ".js", ".ts", ".tsx" ]
    },
 ```
 
Does that explanation make sense? Thanks again for your hard work and for your reply!
