### ISSUE TITLE
Fails silently on JSON read error

### ISSUE THREAD

**Issue by lswest** [smeijer/unimported#22]
My tsconfig.json had an extra comma in it, so the `readJson` was failing silently. It's not really an issue with the tool, but it did take me a while to narrow down the reason why none of my tsconfig paths were being resolved. I ended up figuring it out when I manually added a console.error statement in the catch(e) {} block on line 41 of `fs.ts` and it told me that there was an unexpected `}` in the file. However, just adding that in results in a lot of console statements when I run the jest tests on this project.

Perhaps just printing a warning in the case of tsconfig.json would be sufficient? Or adding a line into the README.md as a possible debug check?

I didn't open a PR for this as I'm not sure if you'd want to handle this, and if you do, what option you'd prefer.

Feel free to close this issue without comment if you don't feel that `unimported` should handle this case.

**Comment by smeijer** [comment]
Thanks for the issue! I think we can fix both problems at once, by changing that function to something like:

```ts
export async function readJson<T extends any>(
  path: string,
  cwd = '.',
): Promise<T | null> {
  try {
    const text = await readText(path, cwd);
    return text ? JSON.parse(text) : null;
  } catch (e) {
    console.error('file does not contain valid json:', path); 
    return null;
  }
}
```

What do you think?
