### ISSUE TITLE
TSconfig support with CRACO

### ISSUE THREAD

**Issue by simonwinter** [smeijer/unimported#26]
Hi there,

Firstly - this is a fantastic project, love your work!

We have a create-react-app, using Typescript with [craco](https://www.npmjs.com/package/@craco/craco) to override some configuration limitations of CRA.

Part of this setup is to use [craco-alias](https://github.com/risenforces/craco-alias#example) - which recommends using a separate tsconfig file (as some options are prevented from being overwritten by CRA), so you get this kind of setup:

tsconfig.json:

```
{
  "extends": "./tsconfig.extend.json",
  "compilerOptions": {
    "target": "es5",
    ...
}
```

tsconfig.extend.json:

```
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "~api/*": ["./api/*", "./api"],
      "~assets/*": ["./assets/*", "./assets"],
      "~components/*": ["./components/*", "./components"],
      ...
    }
  }
}
```

Is there anyway to either get unimported to recognise the `extends` option in `tsconfig.json` so that it can find the aliases contained therein, or to supply additional files to unimported to load?

**Comment by smeijer** [comment]
If that's not (easily) doable, we should add support to import "aliases" from `.unimportedrc.json`. We could use the same syntax there as in the `tsconfig`. This would also resolve #20.

At the end, there are dozens of methods to define aliases, tsconfig, webpack, and there are multiple alias-plugins for babel, all with their own syntax. When we're able to import "ts-like" paths from `.unimportedrc.json`, we support aliases regardless of what build setup is being used.

This logic should be added somewhere here: 

https://github.com/smeijer/unimported/blob/e79798702a8e1db69c0427f5f6eb4162dd7a1b56/src/meta.ts#L22-L60

**Comment by simonwinter** [comment]
Hi @smeijer - I did actually see #20, forgot to mention that! 

Yes, I think the second option of having something in `.unimportedrc.json` would hopefully solve a lot of use cases?

**Comment by simonwinter** [comment]
I'd love to help out!

I guess there are a couple of questions though:

- I think I add to the config (https://github.com/smeijer/unimported/blob/master/src/config.ts) a new key `aliases`?
- If there are aliases already (say inside a tsconfig's compiler options), what strategy do we use? 
  - e.g. do these new aliases remove any existing options, or should we merge?
  - I think we'd just merge?

If you can answer those, I can write a PR for this.

**Comment by smeijer** [comment]
Thanks! 

Naming the prop `aliases` sounds good to me.

I think we can just merge indeed. In the function I linked above, you'll see that we're already merging aliases from package.json with aliases from tsconfig. It only feels right to merge this as well.

**Comment by simonwinter** [comment]
Hi @smeijer - I've just made a PR #28 - which hopefully solves the issue for this & possibly #20 as well 🤞
