### ISSUE TITLE
Component shows up as undetected if imported from aliased path

### ISSUE THREAD

**Issue by agdt3** [smeijer/unimported#27]
Hello,
I have roughly the following setup in my React app:

Webpack overrides (which is what's causing the issue, I think):
`config-overrides.js:`
```
module.exports = {
  webpack: override(
    addWebpackAlias({
      ...
      react: path.resolve(__dirname, './node_modules/react'),
      src: path.resolve(__dirname, './src'),
    }),
```

`src/components/Badge/index.js:`
```
const Badge = () => { ... }

export default Badge;
```

`src/pages/SomePage/SomePage.js:`
```
import Badge from 'src/components/Badge';
...
```

This kind of root import results in `src/components/Badges/index.js` being placed in the `unimported files` list.

If I modify the import to a relative one:
`src/pages/SomePage/SomePage.js:`
```
import Badge from '../../components/Badge';
```
the component is properly detected.

I've also tried modifying the module directory to this, without any effect:
`"moduleDirectory": ["node_modules", "src/"]`

Any suggestion for a workaround? Thanks in advance.

**Comment by alex9pro** [comment]
@agdt3  You can add aliases, the similar works for me

```jsonc
// .unimportedrc.json

{
  "aliases": {
      "components/*": [
          "./src/components",
          "./src/components/*"
      ]
  }
}
```

**Comment by smeijer** [comment]
Thanks for mentioning the solution @alex9pro 

Closing, as this has been revolved by #28

**Comment by agdt3** [comment]
@alex9pro @smeijer It seems to have worked. Thank you for your help!
