### ISSUE TITLE
Use local babel config/plugins

### ISSUE THREAD

**Issue by LandonSchropp** [smeijer/unimported#35]
I've added the smart pipeline operator to my Babel config via a plugin.

``` json
{
  "presets": [ "babel-preset-react-app" ],
  "plugins": [
    [ "@babel/plugin-proposal-pipeline-operator", { "proposal": "smart" } ]
  ]
}
```

When I try to run `unimported`, I get the following error:

```
⠙ resolving imports
Failed parsing /Users/landon/Development/startup/chess-cards/source/javascript/stores/error-store.js
TSError: Expression expected.
    at Object.createError (/Users/landon/Development/startup/chess-cards/node_modules/unimported/node_modules/@typescript-eslint/typescript-estree/dist/node-utils.js:522:12)
    at Object.convertError (/Users/landon/Development/startup/chess-cards/node_modules/unimported/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:36:25)
    at Object.astConverter (/Users/landon/Development/startup/chess-cards/node_modules/unimported/node_modules/@typescript-eslint/typescript-estree/dist/ast-converter.js:15:25)
    at parseWithNodeMapsInternal (/Users/landon/Development/startup/chess-cards/node_modules/unimported/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:328:49)
    at Object.parse (/Users/landon/Development/startup/chess-cards/node_modules/unimported/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:290:21)
    at /Users/landon/Development/startup/chess-cards/node_modules/unimported/dist/traverse.js:133:41
    at Generator.next (<anonymous>)
    at fulfilled (/Users/landon/Development/startup/chess-cards/node_modules/unimported/dist/traverse.js:24:58) {
  fileName: '/Users/landon/Development/startup/chess-cards/estree.tsx',
  index: 1146,
  lineNumber: 56,
  column: 22
}
```

Here's the problem part of the file:

``` js
...

export class ErrorStore {
  ...  

  get title() {
    return this.type |> kebabCase |> replaceAll(#, "-", " ") |> titleCase;
  }

  ...
}
```

Does unimported use my local Babel configuration? Is there a way to configure it to do so?

**Comment by smeijer** [comment]
We don't use local Babel config / plugins at the moment. That sounds like an awesome feature to add tho!

Are you willing to submit a PR?

**Comment by LandonSchropp** [comment]
I'll see if I can find some time to tackle this. I'll report back if it's a little over my head. 🙂

**Comment by LandonSchropp** [comment]
I dug into this a bit and I think this would be a non-trivial refactor. I think the `parse` function inside `traverse.ts` would need to be replaced. Specifically, it looks to me like the `parseEstree` function would have to be replaced with Babel's parser.

I was reading through the `typescript-estree` documentation, and I found this:

> A couple of years after work on this parser began, the TypeScript Team at Microsoft began officially supporting TypeScript parsing via Babel.
> 
> I work closely with the TypeScript Team and we are gradually aligning the AST of this project with the one produced by Babel's parser. To that end, I have created a full test harness to compare the ASTs of the two projects which runs on every PR, please see the code for more details.

So I think this change is possible, but I'm not sure what the level of involvement would be. I'd also worry that swapping out the current parser could break compatibility with existing TypeScript projects. You could do something like swapping the parser if a `.babelrc` file is present, but that might not be a good idea.

Regardless, I think this change is a bit out of my wheelhouse.

**Comment by smeijer** [comment]
Thanks for the research! It sounds doable indeed. So the typescript parser need to be replaced with a Babel parser. And I think the Babel parser needs to load the user config if it exists, and the "Babel typescript" plugin is that one isn't already present.

I do think that part can become tricky, as to my understanding Babel behavior can change depending on the plugin order. But it sounds doable, and I believe the change would be worth it. As we currently don't understand projects with certain "non standard" syntax.

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
