### ISSUE TITLE
use `read-pkg-up` to auto resolve `cwd`

### ISSUE THREAD

**Issue by vjpr** [smeijer/unimported#36]
When using `pnpm`, it requires all dependencies used in code, to be listed in `package.json`.

Many packages violate this.

When I get an error, I want to pass in the file path (from the stack trace) of the file that contains the require that cannot be found.

It should then search upwards to the closest package.json and run from there, telling me which deps are missing from the package.json.

I then add them to `.pnpmfile.cjs`.

Is this possible with `unimported`?

**Comment by smeijer** [comment]
Unimported does show you all the files that you import, but that is not mentioned as a dependency in `package.json`. So I do think so. But I'm unfamiliar with `pnpm`, and also have no idea what `.pnpmfile.cjs` does. So I can't be sure.

Those files should be listed under [`unresolved-imports`](https://github.com/smeijer/unimported#unresolved-imports)

**Comment by vjpr** [comment]
> Unimported does show you all the files that you import, but that is not mentioned as a dependency in package.json.

Yep thats what I need.

---

Can the tool be run like `unimported --cwd=....`?

I guess I can workaround with `(cd ... && unimported)` for now. But would be nice to pass in config file path or all config as cli flags for this use case.

**Comment by smeijer** [comment]
We don't accept a custom work directory as an argument. I'm happy to accept a pull-request for that. I think it's two features that we want:

1. Accept custom work directory as argument
2. Make [initialization a bit smarter](https://github.com/smeijer/unimported/blob/a9cd040351d82fbabfb6a6dc2213d2f18333d926/src/index.ts#L68-L86), so that we can "walk up the tree", until a `package.json` has been found.

The workaround would indeed be to use `cd ... && unimported`

**Comment by vjpr** [comment]
> "walk up the tree"

Sindre's `read-pkg-up` works well for this.

**Comment by smeijer** [comment]
> read-pkg-up

With their `cwd` option, we can support both functionalities at once.

**Comment by smeijer** [comment]
Done. This is available in `v1.15`

It will start looking up to determine the work directory based on the presence of `pacakge.json`. And if you wish to specify a totally different path (down the tree, or a sibling), it's possible to provide a path as positional argument:

```
npx unimported ~/path/to/project
npx unimported ~/path/to/project --no-cache
npx unimported ../sibling
```

**Comment by richardaum** [comment]
Unfortunately looking up for a package.json breaks NX projects where there are multiple package.json per app, but all dependencies are located at the root folder. My suggestion there is to introduce an argument to force the location of the package.json containing the dependencies.

**Comment by smeijer** [comment]
@richardaum does the cwd arg not solve that problem?

> npx unimported ../path
