### ISSUE TITLE
Unable to find unimported files

### ISSUE THREAD

**Issue by dabyland** [smeijer/unimported#41]
First off, I apologize if this is not the preferred channel of communication for these "issues".

I've got Unimported running through my codebases at this point, properly finding unused dependencies. However I am unable to get it to find my unused files. I've even created new files to see if they will be detected but no luck. All of our files are just `.js` extensions. Before adding the `aliases` to my config, I did have unresolved imports, since those issues are fixed I believed it would be able to find my files. 

Here is what my current config looks like:

`.unimportedrc.json`
```
{
	"entry": ["apps/manager/src/index.js"],
	"extensions": [".js"],
	"ignorePatterns": ["**/node_modules/**"],
	"ignoreUnresolved": ["some-npm-dependency"],
	"ignoreUnimported": ["src/i18n/locales/en.ts", "src/i18n/locales/nl.ts"],
	"ignoreUnused": ["create-emotion", "unimported"],
	"aliases": {
		"~/*": ["apps/manager/src/*"],
		"Lib/*": ["lib/node/src/*"],
		"ROOT":  ["./../../*"]
	}
}
```

`My Output`

<img width="678" alt="Screen Shot 2021-07-14 at 2 52 38 PM" src="https://user-images.githubusercontent.com/9575583/125676760-48d81ee5-4850-4036-bd7d-0d635148e0e0.png">

If there's a more appropriate area or contact for these general questions, please let me know.

Thanks in advance,
Danny

**Comment by jesseteal** [comment]
I think I'm having similar issues in that it doesn't appear to be recognizing or respecting my aliases. This may be due to a caching issue.

Try running
```
rm node_modules/.cache/unimported
```
and then re-running unimported.

**Comment by dabyland** [comment]
@jesseteal After you ran that, did it find your unimported files?

**Comment by jesseteal** [comment]
I had the reverse problem. It wouldn't stop telling me that files were unimported even though they were. I didn't have aliases set up on the first run and it reported 500 unimported files.  I added the proper alias but it continued to incorrectly report them.  After clearing the cache file it dropped the unimported list to 157.

Have you tried changing your aliases to use relative paths?  Like:
```
"~/*": ["./apps/manager/src/*"],
"Lib/*": ["./lib/node/src/*"],
...
```
I think it might be trying to turn your aliases into paths relative to the disk root.  So instead of `/Users/dabyland/RepoFolder/project/apps/manager/src/*` you are getting `/apps/manager/src/*

**Comment by smeijer** [comment]
@jesseteal are you using 1.12? Do you have the same trouble when 1.11?

I see in the screenshot that @dabyland is using 1.11. The cache has been introduced by 1.12. So that can't be the issue.

Incorrect mapping of aliases sounds more likely.

**Comment by smeijer** [comment]
Any chance you can make a small repo @dabyland?

**Comment by dabyland** [comment]
@smeijer [Here](https://github.com/dabyland/unimported-repo) is a very basic version of the repo that I was having issues with. I created a couple of files in this one, one of which is imported and the other is not. It doesn't seem to be catching that but again, I'm sure there's something I'm missing here. It is however catching my unused dependencies.

**Comment by smeijer** [comment]
Figured it out. Thanks for the repo, that helped a lot!

So, the first thing in your repo that got me, was having a capital `I` in the filename of `Index.js`, while it's named `index.js` in an entry file in the config. 

Next, and that's a bug in unimported, you only have a single extension specified in your config under the `extensions` property. I'm going to push a fix soon. In the mean while, you can check by just adding another extension there as well (`[".js", ".ts"]` for example).

**Comment by smeijer** [comment]
Ok, new version has been published. Can you give it a shot and let me know if it worked? This is the output I get on your test project: (after renaming `Index.js` to `index.js`)

![image](https://user-images.githubusercontent.com/1196524/127391964-ecd4454b-5b4e-48c2-8f4f-9f638bb9ea34.png)

**Comment by dabyland** [comment]
Works like a charm, thanks for all the help and amazing tool!

**Comment by smeijer** [comment]
Sweet!
