### ISSUE TITLE
All of my files are unresolved imports (react)

### ISSUE THREAD

**Issue by timworx** [smeijer/unimported#43]
Hey all,
Looking forward to using unimported, but having trouble getting it working.
It is a react project, created with Create React App.
One difference from standard CRA setup, I've set `NODE_PATH='src/'`
and most of my imports look like `import Component from components/Component`

Current config I've tried

```
{
  "ignoreUnresolved": [],
  "ignoreUnimported": [],
  "ignoreUnused": [],
  "moduleDirectory": ["node_modules", "src/"],
  "rootDir": "./src",
  "extensions": [".jsx", ".js"],
  "ignorePatterns": [
    "**/node_modules/**",
    "**/*.stories.{js,jsx,ts,tsx}",
    "**/*.tests.{js,jsx,ts,tsx}",
    "**/*.test.{js,jsx,ts,tsx}",
    "**/*.spec.{js,jsx,ts,tsx}",
    "**/tests/**",
    "**/__tests__/**",
    "**/*.d.ts"
  ]
}
```
Tried with/without rootDir and moduleDirectory, no difference.
Either way, it appears that nearly all my files are missed with unresolved imports, so they show as unimported files. 

I've also tried with aliases:

```
"aliases": {
      "views/*": [
          "./views",
          "./views/*"
      ],
      "components/*": [
          "./components",
          "./components/*"
      ]
  },```

**Comment by smeijer** [comment]
Can you make a small repo for me to run some tests on?
