### ISSUE TITLE
Add support for jsconfig and baseUrl

### ISSUE THREAD

**Issue by theahura** [smeijer/unimported#44]
First, this is a really helpful tool, thank you for making it. 

I have a file structure that looks something like:
```
src/
-- presentation/
---- client.js
---- api.js
```

api is imported by client.js using an absolute import from the src directory:
`import * as api from '/presentation/api.js'`

However, this is not picked up by unimported, I get the following output:
```
Unresolved import:
presentation/api.js

Unimported files:
src/presentation/api.js
```

In my jsconfig, I set the root to src, like so:
```
{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}
```
to enable the absolute imports.

Do you know how to make this work?

**Comment by smeijer** [comment]
I don't think that's currently supported, but I'm definitely willing to add that.

Are you able to work on a pull request?

**Comment by theahura** [comment]
Unfortunately probably not. I added it to my todo list in case I have some free time, but I don't expect to have much free time to really dig in for at least a month. Still, interested in tracking the feature.

**Comment by smeijer** [comment]
Turns out, I was mistaken. This is currently supported. We support both absolute imports, as well as `compilerOptions.rootDir`. We don't support `baseUrl` tho, and to be honest, I'm also not entirely sure about the difference between those two.

**Comment by theahura** [comment]
I'm not sure about the difference either, and poking around doesn't help much except to note that baseURL is what is needed for absolute imports. :shrug: 

Adding `compilerOptions.rootDir = "src"` did not fix the issue. Is there something specific I need to set to make absolute imports work? It looks like unimported expects the imports to include `src/` but not sure how to tell the program to ignore that path prefix

**Comment by smeijer** [comment]
I've just published a new version, which should add support for `jsconfig` files, as well as `baseUrl`.

I've created a repo with the script below. Running `npx unimported` in that directory, results in:

```shell
✓ There don't seem to be any unimported files.
```

repo:

```shell
mkdir -p repo/src/presentation
cd repo
echo 'export const api = {}' > src/presentation/api.js
echo 'import * as api from "/presentation/api.js"' > src/presentation/client.js
echo '{ "main": "src/presentation/client.js" }' > package.json
echo '{ "compilerOptions": { "baseUrl": "src" } }' > jsconfig.json
```

**Comment by smeijer** [comment]
Can you confirm that it works?

**Comment by anonrig** [comment]
I'm having the same exact issue with the following jsconfig on my nextjs project. I import dependencies with the following syntax: 

`import DashboardLayout from 'components/page-layout/DashboardLayout'`

``json
{
  "compilerOptions": {
    "baseUrl": ".",
    "checkJs": true,
    "jsx": "react"
  }
}
```

dashboard layout is in unresolved imports list:

```
  19 │ components/page-layout/DashboardLayout
```

**Comment by smeijer** [comment]
@anonrig have you tried adding an alias for `components`?
