### ISSUE TITLE
tsconfig json with comments is not supported

### ISSUE THREAD

**Issue by Shivam60** [smeijer/unimported#49]
Hey 

`npx unimported` is failing with the error 
`
file does not contain valid json: tsconfig.json error:  SyntaxError: Unexpected token / in JSON at position 59
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\shchaw\AppData\Roaming\npm-cache\_npx\29832\node_modules\unimported\dist\fs.js:67:32)
    at Generator.next (<anonymous>)
^TSyntaxError: Unexpected token / in JSON at position 59^T^C
`
P.S my tsconfig does not even have 30 lines

**Comment by smeijer** [comment]
Your tsconfig file isn't valid json, it probably contains some comments. We don't support that at this moment.

**Comment by smeijer** [comment]
Happy to accept a pull request that uses [json5](https://www.npmjs.com/package/json5)  to parse the json here:

https://github.com/smeijer/unimported/blob/6437a95b55b5735dfe977acc3e769305a3e92322/src/fs.ts#L36-L47

**Comment by FlorianWendelborn** [comment]
I just wanted to implement this as it’s fairly straight-forward. After forking, I noticed it’s already in fa7aa13d647f4526d2bfff4a765e3f659ff459e1. Maybe this issue could be closed, or are you waiting until it’s released to NPM?

**Comment by smeijer** [comment]
I usually wait with closing until I've published. The closure might trigger notifications for people watching the issue, which is confusing if the version that fixes it hasn't been published yet.

I'll finish a few things up, and publish in a couple hours from now.

**Comment by smeijer** [comment]
Supported in `v1.18` :sunglasses:

**Comment by Shivam60** [comment]
Thanks for quick resolution
