### ISSUE TITLE
README can make more emphasis on clearing the cache after modifications to the config file

### ISSUE THREAD

**Issue by jospablos** [smeijer/unimported#50]
Excellent tool! Sharing my experience to improve it:

Basically, I ran the tool first (granted, my bad for not reading the whole README) and got a bunch of unresolved imports for the ones relying on aliases... I tried a bunch of configurations based on the README that didn't get me correct results, which sent me to other tools and then back to [this issue's comment](https://github.com/smeijer/unimported/issues/45#issuecomment-891278230), which puzzled me more that it worked on a test project but not on mine... so after poking into the code and about an hour of flailing, I found that the issue was that I was getting the cached results!

So I wanted to volunteer some possible improvements to the README to reduce the chance of this happening to others like me. How about:
1. Adding a section about running in CRA projects, offering the config snippet `'{ "aliases": { "*": "src/*" } }'`?
2. Adding a troubleshooting section, pointing people to delete the cache after doing any modification to the config file? or a more prominent explanation in the main config section.

Thanks for making `unimported`!

**Comment by smeijer** [comment]
Hi, thanks for opening the issue.

Your suggestions sounds great, and I'm happy to merge any PR that improves documentation.

The cache file indeed needs purging when the config file has changed. I should also fix that, as it's a bit annoying.

**Comment by smeijer** [comment]
The readme hasn't changed in this area, but for what it's worth this cache issue should be less of a problem due to some changes in the caching area.

There is still some work to do, so I'm keeping the issue open.

**Comment by smeijer** [comment]
I've renamed `gotchas` to `troubleshooting`, and added cache issues to that. Would that have spared you the troubles?

https://github.com/smeijer/unimported#troubleshooting

Also, I'm curious about the "other tools" that you've been looking at. I'd like to list them in the readme as well if they are comparable. Do you remember which ones you've looked at?

**Comment by alk-mandrianarijaona** [comment]
Hi, here are one other tool I tried for similar purpose : https://github.com/nadeesha/ts-prune

**Comment by smeijer** [comment]
Thanks. Ts-prune is not really the same tho. They scan for unused exports, while unimported reports unused files.
