### ISSUE TITLE
Fix Vue <script lang="ts"> Detection

### ISSUE THREAD

**Issue by FlorianWendelborn** [smeijer/unimported#51]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `unimported@1.17.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/unimported/dist/traverse.js b/node_modules/unimported/dist/traverse.js
index e621f6b..607e491 100644
--- a/node_modules/unimported/dist/traverse.js
+++ b/node_modules/unimported/dist/traverse.js
@@ -127,7 +127,7 @@ function extractFromScriptTag(code) {
     let end = -1;
     // walk the code from start to end to find the first <script> tag on it's own line
     for (let idx = 0; idx < lines.length; idx++) {
-        if (lines[idx].trim() === '<script>') {
+        if (lines[idx].trim() === '<script>' || lines[idx].trim().startsWith('<script ')) {
             start = idx;
             break;
         }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

---

Here is the context: https://github.com/smeijer/unimported/issues/19#issuecomment-894331854

Please note that the space in `<script ` is important, as I actually ran into a component called `<script-editor-input>` in our codebase...

**Comment by smeijer** [comment]
`v1.18` has much better support for script tag styles. Hope that helps.
