### ISSUE TITLE
`@types/*` packages are detected as 'unused dependencies'

### ISSUE THREAD

**Issue by okunishinishi** [smeijer/unimported#52]
ts projects have a lot of `@type/*` dependences and they are detected as 'unused dependencies'.

<img width="363" alt="Screen Shot 2021-08-08 at 21 38 04" src="https://user-images.githubusercontent.com/745662/128632211-14578aef-ee41-42ad-97ac-5da3bfb0455b.png">

Needs config like "ignoreUnusedPattern"

**Comment by smeijer** [comment]
There is a `ignorePatterns` option. Does that help?

```json
{
  "ignorePatterns": ["@types/**"]
}
```

**Comment by smeijer** [comment]
Types should also be installed as devDependency, and devDependencies shouldn't be reported. Did you install them as normal dependency?

**Comment by okunishinishi** [comment]
> Did you install them as normal dependency?

Yes, I installed as normal dependency. 

And you are right.  I did some google searching and now understand that they should be in devDependency.
Sorry for my ignorance, thanks for replying. 

I'm closing this issue.
