### ISSUE TITLE
Can't use a general selector to ignore all PNG files

### ISSUE THREAD

**Issue by nathanielgrossman** [smeijer/unimported#54]
Hello,

First of all, thank you for building this tool!

The repo I'm using it in has lots of png files with pixel density suffixes (i.e. `image@1x.png`). Since these images are imported without stating the specific suffix, it seems that Unimported is flagging many of them as being unresolved imports. We already have another test to check for unused images so I'd prefer to just exclude all png files from Unimported's check. When I run the command with the `-u` flag it finds and ignores all the png imports, but since this is a large repo with hundreds of images it generates a very large config file. I would prefer to use a generalized selector to ignore all pngs. I have tried many different ways of doing this but none of them work. Here is a sample of what the ignored imports look like when the config file is automatically generated (I've only included a few images for brevity's sake):

```
{
  "entry": ["index.android.js", "index.ios.js"],
  "aliases": {
    "@images/*": ["./javascript/images/*", "./javascript/images/**"]
  },
  "extensions": [".ts", ".js", ".tsx", ".jsx"],
  "ignoreUnresolved": [
    "../images/arrow-left-gray-small.png",
    "../images/arrow-left-white.png",
    "../images/close-gray-bold.png",
    "../images/close-gray.png",
    "../images/close-white-bold.png",
    "@images/info-request/edit-message.png",
    "@images/info-request/info-requested.png",
    "@images/info-request/message-sent.png",
    "@images/journey.png",
    "@images/nye-clock.png",
    "@images/phone-white.png"
  ],
  "ignoreUnimported": [],
  "ignoreUnused": [],
  "ignorePatterns": [
    "**/node_modules/**",
    "**/*.stories.{js,jsx,ts,tsx}",
    "**/*.tests.{js,jsx,ts,tsx}",
    "**/*.test.{js,jsx,ts,tsx}",
    "**/*.spec.{js,jsx,ts,tsx}",
    "**/tests/**",
    "**/__tests__/**",
    "**/*.d.ts",
    "**/*.png",
    "server/**",
    "javascript/graphql/__generated__/**",
    "android/**",
    "__mocks__/**",
    "@images/**",
    "@images/*"
  ]
}
```
And here's my attempt at using a more general selector to ignore all pngs and all imports from the `@images` alias.

```
{
  "entry": ["index.android.js", "index.ios.js"],
  "aliases": {
    "@images/*": ["./javascript/images/*", "./javascript/images/**"]
  },
  "extensions": [".ts", ".js", ".tsx", ".jsx"],
  "ignoreUnresolved": ["@images/*", "@images/**", "@images/**/**", "**/*.png"],
  "ignoreUnimported": [],
  "ignoreUnused": [],
  "ignorePatterns": [
    "**/node_modules/**",
    "**/*.stories.{js,jsx,ts,tsx}",
    "**/*.tests.{js,jsx,ts,tsx}",
    "**/*.test.{js,jsx,ts,tsx}",
    "**/*.spec.{js,jsx,ts,tsx}",
    "**/tests/**",
    "**/__tests__/**",
    "**/*.d.ts",
    "**/*.png",
    "server/**",
    "javascript/graphql/__generated__/**",
    "android/**",
    "__mocks__/**",
    "@images/**",
    "@images/*"
  ]
}
```

I'm sure this is user error, but do you have any idea what I'm doing wrong? Thank you!

**Comment by smeijer** [comment]
Closing as covered by #103
