### ISSUE TITLE
Different results in GHA and local machine

### ISSUE THREAD

**Issue by sk-** [smeijer/unimported#55]
In my local machine (macOs 10.15.14) when I run unimported version v1.19.0 I see no errors when I run unimported. However when running it on GHA, I get the following false positive

```
       summary               unimported v1.19.0 (node)
───────────────────────────────────────────────────
       entry file          : src/index.jsx

       unresolved imports  : 0
       unused dependencies : 0
       unimported files    : 1


─────┬───────────────────────────────────────
     │ 1 unimported files
─────┼───────────────────────────────────────
   1 │ src/Components/xxx/XXX.jsx
─────┴───────────────────────────────────────
```

Is there any way to debug this?

**Comment by angelos3lex** [comment]
Would expect this to be an issue with some cache or different dependencies for example, do you include package-lock.json file in your gha build?

**Comment by sk-** [comment]
Yes we are including `package-lock.json`. What's weird is that the reported file is one of our source files.

However, I tried it again and the file is actually unused now. Maybe it was an error on my side, if so sorry for the noise.

**Comment by smeijer** [comment]
Sounds like the github action was running on another branch than the one you were looking at. Glad to see that it has been resolved. 🙂
