### ISSUE TITLE
Feature request: warn if file is imported

### ISSUE THREAD

**Issue by gajus** [smeijer/unimported#61]
We are trying to add `unimported` to our CI/CD build pipeline.

The goal is to reduce accumulation of dead files.

However, sometimes, files that are being worked on, might not be included in any of the pages, e.g. they are being developed as stand alone UI components in a storybook.

In those cases, we want to adopt a convention that we exclude files that match `__incomplete__` pattern.

The catch is that we do not want to allow any of these files to be imported into pages, i.e.

Would like a rule that alerts when files matching a pattern _are_ included in entries.

**Comment by smeijer** [comment]
I've given it a thought, and "warn if file is imported", is the opposite of what this project is designed to do "warn if file is not imported anywhere". I'm closing this ticket, as I believe it's out of scope.

Thanks for the suggestion.
