### ISSUE TITLE
Feature: Output to File

### ISSUE THREAD

**Issue by bmeverett** [smeijer/unimported#7]
Hi there 👋

I started to take a look at this and use it in my projects. I noticed one thing that may be useful and if it's already a feature and I missed it then sorry! While the command output is great, it would be nice to specifiy and option to write that to a file. Especially if you use this on a large project for the first time, there may be a lot of things to go through and you may want to reference back to it. 

I'm happy to take a look to see what it would take to implement this.

**Comment by smeijer** [comment]
Hi!

Thanks for the suggestion. 

I agree that it would be nice to add support for `output-file` and `format` arguments, in a similar way as [eslint](https://eslint.org/docs/1.0.0/user-guide/command-line-interface#options-214):

```
Options:
  -f, --format String             Use a specific output format - default: stylish
  -o, --output-file path::String  Specify file to write report to
```

Besides the case that you mention, ("first time usage"), I think this would also be useful when running in a CI. The output files can then easily be exported as "artifact". 

A pull-request would be most welcome!

As a starting point, I think this is where you want to hook it into (it's the call to our first and only formatter):

https://github.com/smeijer/unimported/blob/3472570b09e88a80e3288dd18bdceea8a4fe41d7/src/index.ts#L142-L144

The current formatter is: https://github.com/smeijer/unimported/blob/3472570b09e88a80e3288dd18bdceea8a4fe41d7/src/print.ts#L62

**Comment by bmeverett** [comment]
Do you want this as it's own formatter, or as part as `printResults` So basically do you want 
```
else {
printResults(result,context)
writeToFile()
```

Or just add the calls to write to a file inside the `printResults` method

**Comment by smeijer** [comment]
I think we need to adjust the current "formatter" (`print.ts`) to return a string, instead of calling `console.log` everywhere.

And then in `index.ts`, handle the returned string from `printResults` and write or print based on `args.output`.

**Comment by smeijer** [comment]
Closing this for housekeeping. If anyone is willing to take a shot in implementing custom formatter, then I'm happy to add the functionality. 

Untill then, `npx unimported > results.log` works just fine.
