### ISSUE TITLE
Add support for "workspaces"

### ISSUE THREAD

**Issue by matthieusieben** [smeijer/unimported#70]
The way I see this, given the following file structure
```
<root>/package.json // defines "workspaces"
<root>/.unimportedrc.json // defines "entries" as ["src/*"]
<root>/packages/<package_name>/package.json
<root>/src/<app_name>/package.json
```

We should ideally be able to call `unimported` from the root and detect both
- errors within packages (same as running `npx unimported` from every folder)
- packages not use by any "entry" defined in the <root>/.unimportedrc.json

**Comment by smeijer** [comment]
I agree with the use case. But doesn't this already work when using a tool like lerna?

**Comment by matthieusieben** [comment]
yes but then you have to write a `script` in every single package, which can be quite a lot of copy paste

**Comment by matthieusieben** [comment]
also, you would not be able to detect packages that are not used by any other

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
