### ISSUE TITLE
Instructions for TypeScript baseUrl or rootDir not clear.

### ISSUE THREAD

**Issue by jackel119** [smeijer/unimported#76]
I'm trying to figure out how to use unimported with my project, but I can't seem to get it to work with TypeScript `baseUrl` paths.

The repository is [here](https://github.com/jackel119/personal-blog).

I've tried added a "rootDir" option as mentioned in the README, but it doesn't seem to do anything. I also tried replacing "rootDir" with "baseUrl" as that's mentioned in a code snippet in #34.

**Comment by smeijer** [comment]
Hi!

It looks like you need to define a few `aliases` as well.

```json
{
  "rootDir": "./src",
  "aliases": {
    "components/*": ["./components", "./components/*"],
    "hooks/*": ["./hooks", "./hooks/*"]
  }
}
```

Please let me know if this helps.

**Comment by jackel119** [comment]
This works, thank you!
