### ISSUE TITLE
Unimported file doesn't get flagged

### ISSUE THREAD

**Issue by itsameandrea** [smeijer/unimported#79]
Hello there!

I have a node/react project where I'm using `unimported`. This project was using `babel` and `rollup` for transpiling and `bundling`. Now we're in the process of migrating that to `esbuild`. Probably this has no impact on `unimported` but I still wanted to mention it, just in case.

In this project I have a file `sites/demo/start.js` that is importing another file `sites/demo/config.js`. If I comment out that import statement and run `unimported` then `config.js` doesn't get flagged as unimported. I tried this also after clearing out the cache.

```
// import config from './config'

console.log('Config: ', config)
```

I created a simplified [repo](https://github.com/ilrock/dumbed_down_sites) that sort of replicates the project setup and still was able to replicate the issue.

In the `.unimportedrc.json` I set `sites/demo/start.js` as the entry

```
{
  "entry": [
    "sites/demo/start.js"
  ],
  "ignorePatterns": [
    "**/src/**",
    "**/node_modules/**"
  ],
  "ignoreUnused": [
    "@mailchimp/mailchimp_marketing",
    "@sendgrid/mail",
    "body-parser",
    "dotenv",
    "express",
    "express-basic-auth",
    "stripe",
    "unimported",
    "winston",
    "xml-js"
  ]
}
```

So I was expecting `config.js` to be flagged.

Could there be a clash between the two setups that we're running in parallel (`rollup` and `esbuild`)?

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
