### ISSUE TITLE
1.19.1 is Missing

### ISSUE THREAD

**Issue by FlorianWendelborn** [smeijer/unimported#80]
It is neither in the latest [`package.json`](https://github.com/smeijer/unimported/blob/8e889d5bec25faae9457120642d4b69f635e8e05/package.json#L3) nor in the [Releases](https://github.com/smeijer/unimported/releases)

Is `1.19.1` a real version? Or did someone malicious take over this package?

**Comment by smeijer** [comment]
No worries, I simply forgot to push.
