### ISSUE TITLE
🔓 Update simple-git to a secure version

### ISSUE THREAD

**Issue by BevanR** [smeijer/unimported#82]
The `unimported` package depends on `simple-git` v2.38 which has severe vulnerabilities. They are fixed in `simple-git` v3.0.3.

**Comment by smeijer** [comment]
Sorry for the silence. I'll get on this asap.

**Comment by smeijer** [comment]
Released with https://github.com/smeijer/unimported/releases/tag/v1.20.0. Thanks for the heads up, and apologies for the delay.

**Comment by BevanR** [comment]
@smeijer All good! We appreciate your effort! 🙂
