### ISSUE TITLE
`ignoreUnimported` does not work with relative paths as of 1.20.0

### ISSUE THREAD

**Issue by plof27** [smeijer/unimported#90]
When using `unimported` version 1.20.0, it seems only absolute file paths are supported for the `ignoreUnimported` setting. I noticed this when, after updating, I was suddenly getting unimported errors for files that were previously being ignored. Running `npx unimported -u` only adds absolute paths to the config file, and changing them to relative paths causes them to stop working.

This is not only a breaking change with previous versions of `.unimportedrs.json`, but also causes issues when sharing config across team members.

Tested on Windows 10 with a [Meteor](https://www.meteor.com/) project using Meteor version 2.7.1. I'm not sure if this replicates across other types of projects, or if it's a meteor-specific issue.

**Comment by krzysiekplesniak** [comment]
We have this same trouble/issues, so we decided to restore version 1.19.1
And it works perfectly now

**Comment by smeijer** [comment]
A pull to get this fixed would be much appreciated ❤️

**Comment by smeijer** [comment]
I've tried to reproduce this, but the issue does not exist on my mac and linux machines. Unfortunately, I'm unable to test on a windows device at this moment.

For anyone willing to try, here's a quick script to setup a minimal test case:

**prepare the test case**
```
mkdir -p unimported-repo
cd unimported-repo
echo 'export const api = {}' > index.js
echo '{ "main": "index.js" }' > package.json
echo '' > dangling.js
```

**test runs**
```
npx unimported@1.19.0 -u && cat .unimportedrc.json
npx unimported@1.20.0 -u && cat .unimportedrc.json
```

In both cases, my output is:

```json
{
  "ignoreUnresolved": [],
  "ignoreUnused": [],
  "ignoreUnimported": [
    "dangling.js"
  ]
}
```

Again, I believe this is a Windows issue, but I have no machine to test that.

**Comment by LandGod** [comment]
Just ran this on my Windows machine. Here is what I got:
> OS Name: Microsoft Windows 10 Pro
> Version: 10.0.19044 Build 19044
> System Type: x64-based PC

unimported@1.19.0:
```JSON
{
  "ignoreUnresolved": [],
  "ignoreUnused": [],
  "ignoreUnimported": [
    "dangling.js",
    "index.js"
  ]
}
```

unimported@1.20.0:
```JSON
{
  "ignoreUnresolved": [],
  "ignoreUnused": [],
  "ignoreUnimported": [
    "C:/Users/Dan/Documents/Programming/Misc/unimported-repo/dangling.js",
    "C:/Users/Dan/Documents/Programming/Misc/unimported-repo/index.js"
  ]
}
```

---

After trying the above, I then went back and added an export from `dangling.js` and then imported it in `index.js` just to establish a control, and here is what I got: 

```javascript
// dangling.js
export const POTATO = "Potato"
```

```javascript
// index.js
import { POTATO } from "./dangling"

console.log(POTATO);

export const api = {}
```

unimported@1.19.0 (with import from dangling):
```JSON
{
  "ignoreUnresolved": [],
  "ignoreUnused": [],
  "ignoreUnimported": [
    "index.js"
  ]
}
```

unimported@1.20.0 (with import from dangling):
```JSON
{
  "ignoreUnresolved": [],
  "ignoreUnused": [],
  "ignoreUnimported": [
    "C:/Users/Dan/Documents/Programming/Misc/unimported-repo/index.js"
  ]
}
```
---

Finally, I went and opened up my MacBook, which is currently running MacOS (Big Sur) and ran the original test cases again. When running on MacOS, my results matched @smeijer.

**Comment by smeijer** [comment]
@LandGod Thanks! And if you were to revert #68, does that change things? That's the commit I suspect from breaking stuff.

```
git revert 76d9caf
```

**Comment by smeijer** [comment]
Ok, I've updated the GitHub action to also run test cases on Windows, which indeed [failed miserably](https://github.com/smeijer/unimported/runs/6638708590?check_suite_focus=true#step:5:1018). Then I added some fixes, and now I have [all green flags](https://github.com/smeijer/unimported/runs/6639090526?check_suite_focus=true).

**Comment by smeijer** [comment]
Published. Can someone try with `1.20.1`?

```shell
mkdir -p unimported-repo
cd unimported-repo
echo 'export const api = {}' > index.js
echo '{ "main": "index.js" }' > package.json
echo '' > dangling.js

npx unimported@1.20.1 -u && cat .unimportedrc.json
```

**Comment by LandGod** [comment]
Ran again on windows with the update and it's looking great. Thank you 😄 

```JSON
{
  "ignoreUnresolved": [],
  "ignoreUnused": [],
  "ignoreUnimported": [
    "dangling.js"
  ]
}
```

**Comment by smeijer** [comment]
Sweet! Thanks for letting me know.
