### ISSUE TITLE
feat: support unimported assets like json,png,svg

### ISSUE THREAD

**Issue by alois-beto** [smeijer/unimported#91]
In `react-native` we can import regular code files (.js, .jsx, .ts, .tsx) but we can also import assets files like json, png, svg...

How can I configure the script to get unsused assets in "unimported files" section?

I tried adding `".png", ".json"` to `extensions` in `.unimported.json` but it fails because it tries to parse the files 😕

(Great tool btw)

**Comment by smeijer** [comment]
I'm happy to accept a pull request, if anyone is up to it.

**Comment by yyamanoi1222** [comment]
@smeijer 
Hi!
Are there any progress or implementation policy about this issue?
If you have any ideas, could you let me know.
I'm going to contribute it!

**Comment by smeijer** [comment]
There's no progress on this topic, but I'm still happy to accept a pull request for it.

**Comment by smeijer** [comment]
Sounds good, tho I wonder if we need to specify the extensions. Can't we just assume that every file that isn't a supported extension, is an asset?

**Comment by yyamanoi1222** [comment]
@smeijer 
If we regarded every files that isn't a supported extension as assets, i think that many files are detected as unused files.
So we have to specified extensions that have a possibility to import from codes.

**Comment by smeijer** [comment]
I was thinking that those files might be excluded via `ignorePatterns`. But your solution sounds easier to grasp & configure for beginners. Let's go with that. Thanks.
