### ISSUE TITLE
Add support to finding unimported functions and variables

### ISSUE THREAD

**Issue by armouti** [smeijer/unimported#94]
Can support be added to finding and listing:
1- Files containing functions that are imported elsewhere but unused 
2- Exported functions that are not imported anywhere, in files that have other functions being exported/imported ?

**Comment by smeijer** [comment]
It can, but I'm not sure if we should. That's a feature current linters already support.

**Comment by gajus** [comment]
Seems like this is not a bug, but just unsupported feature

https://github.com/smeijer/unimported/issues/107

@armouti Have you found libraries that help to identify unused functions?
