### ISSUE TITLE
[Request] Allow specifying entryFiles directly

### ISSUE THREAD

**Issue by Nantris** [smeijer/unimported#96]
The reason for this would be to allow different aliases in different entry points.

**Comment by smeijer** [comment]
By directly, do you mean as a command-line argument?

**Comment by Slapbox** [comment]
Thanks for your reply @smeijer! I mean like mentioned [in this comment.](https://github.com/smeijer/unimported/issues/20#issuecomment-1147956546)

**Comment by smeijer** [comment]
This project is being archived. Please check the readme for more info.
